Line 29: Code doesn't exit in this error handling, but it does if there are no errors (near line 31)
Line 42: Code doesn't exit in this `done` call, instead it exits in `then` call near line 37
Line 44: Code doesn't exit in this error handling, but it does in error handling near line 40